name: Build Release Binaries for twitter

on:
  [ workflow_dispatch ]

jobs:
  build-the-mod:
    runs-on: ubuntu-latest
    name: Create The Twitter mod
    steps:
      # Setup Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.3.1

      - name: Download twitter
        run: wget 'https://www.dropbox.com/s/qc45xv8hw4idphn/twitter.apk?dl=0'
      - name: rename
        run: mv 'twitter.apk?dl=0' twitter.apk

      - name: Permission setup
        run: chmod +x cmd-twitter.sh

      - name: Build
        run: ./cmd-twitter.sh

      - name: Output the mod
        uses: actions/upload-artifact@v3
        with:
          name: revd-yt.apk
          path: twitter-ReVanced.apk
