name: Build Release Binaries

on:
  [ workflow_dispatch ]

jobs:
  build-the-mod:
    runs-on: ubuntu-latest
    name: Create The Youtube mod
    steps:
      # Setup Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.3.1

      - name: Download yt
        run: wget 'https://www.dropbox.com/s/9gmfqw5d86qmxbw/yt.apk?dl=0'

      - name: list files
        run: ls -lah

      - name: Permission setup
        run: chmod +x cmd.sh

      - name: Build
        run: ./cmd.sh

      - name: Output the mod
        uses: actions/upload-artifact@v3
        with:
          name: revd-yt.apk
          path: yt-ReVanced.apk
